name: japanese_restaurant_app
description: A new Flutter project.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.1.0-262.0.dev <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  google_fonts: ^5.1.0
  hive_flutter: ^1.1.0
  lottie: ^2.6.0
  intl: ^0.18.1
  flutter_slidable: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
   - assets/img/
   - assets/img/maki/
   - assets/img/nigiri/
   - assets/img/other/
   - assets/img/popular/
   - assets/lottie/

flutter_intl:
  enabled: true
